// Generated by CoffeeScript 1.3.3
(function() {
  var FileAdaptor, fs, util;

  fs = require("fs");

  util = require("util");

  FileAdaptor = (function() {

    function FileAdaptor(fileName) {
      this.fileName = fileName;
    }

    FileAdaptor.prototype.load = function(cb) {
      return fs.readFile(this.fileName, 'utf8', function(err, data) {
        var json;
        if (err) {
          return cb(err);
        } else {
          json = JSON.parse(data);
          return cb(null, json.items, json.assignments, json.children);
        }
      });
    };

    FileAdaptor.prototype.save = function(items, assignments, children, cb) {
      var data, json;
      json = {
        items: items,
        assignments: assignments,
        children: children
      };
      data = JSON.stringify(json);
      return fs.writeFile(this.fileName, 'utf8', data, function(err, data) {
        if (err) {
          return cb(err);
        } else {
          return cb();
        }
      });
    };

    return FileAdaptor;

  })();

  module.exports = FileAdaptor;

}).call(this);
